name: lando-pma-4
services:
  pma:
    type: phpmyadmin:4.9
    hosts:
      - database
      - database2
  pma_theme:
    type: phpmyadmin:4.7
    hosts:
      - database
      - database2
    config:
      config: .lando/config.user.inc.php
    build_as_root:
      - chmod +x /app/.lando/pma-theme.sh
      - /app/.lando/pma-theme.sh
  database:
    type: mariadb
  database2:
    type: mariadb
