name: lando-pma
services:
  pma:
    type: phpmyadmin:5.1
    hosts:
      - database
      - database2
  pma_theme:
    type: phpmyadmin:5.0
    hosts:
      - database
      - database2
    config:
      config: .lando/config.user.inc.php
    build_as_root:
      - apt-get update -y
      - apt-get install openssl wget unzip -y
      - rm -rf /var/cache/apk/*
      - chmod +x /app/.lando/pma-theme.sh
      - /app/.lando/pma-theme.sh
  database:
    type: mariadb
  database2:
    type: mariadb

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/phpmyadmin": ./../../
  "@lando/mariadb": ./node_modules/@lando/mariadb
